#pragma once
#include <Windows.h>
#include <iostream>
#include <thread>
#include <TlHelp32.h>
#include <atomic>
#include <ctime>
// Program
#include "global.h"
#include "config.h"
#include "memory.h"
#include "menu.h"
// Awareness
#include "glow.h"
#include "radar.h"
#include "chams.h"
#include "sonar.h"
#include "hitsound.h"
#include "lessflash.h"
// Combat
#include "rcs.h"
#include "aim.h"
#include "slowaim.h"
#include "trigger.h"
// Misc
#include "automation.h"
#include "fov.h"