<?php
return array (
  'admin_permission.addOn' => 'Manage add-ons',
  'admin_permission.advertising' => 'Manage advertising',
  'admin_permission.attachment' => 'Manage attached files',
  'admin_permission.ban' => 'Manage bans',
  'admin_permission.bbCodeSmilie' => 'Manage BB codes and smilies',
  'admin_permission.blacktea_steamauth' => 'Steam Auth',
  'admin_permission.cron' => 'Manage cron entries',
  'admin_permission.help' => 'Manage help',
  'admin_permission.import' => 'Import data',
  'admin_permission.language' => 'Manage languages and phrases',
  'admin_permission.mjstSupport' => '[BRST] Manage support tickets',
  'admin_permission.navigation' => 'Manage navigation',
  'admin_permission.node' => 'Manage nodes',
  'admin_permission.notice' => 'Manage notices',
  'admin_permission.option' => 'Manage options',
  'admin_permission.payment' => 'Manage payment providers',
  'admin_permission.rebuildCache' => 'Rebuild caches',
  'admin_permission.siropuReferralContests' => 'Manage Referral Contests',
  'admin_permission.style' => 'Manage styles, style properties, and templates',
  'admin_permission.tags' => 'Manage tags',
  'admin_permission.thReactions' => 'Manage [TH] Reactions',
  'admin_permission.thread' => 'Manage threads and posts',
  'admin_permission.trophy' => 'Manage trophies',
  'admin_permission.user' => 'Manage users and moderators',
  'admin_permission.userField' => 'Manage custom user fields',
  'admin_permission.userGroup' => 'Manage user groups',
  'admin_permission.userUpgrade' => 'Manage user upgrades',
  'admin_permission.viewLogs' => 'View logs',
  'admin_permission.viewStatistics' => 'View statistics',
  'admin_permission.warning' => 'Manage warnings',
  'admin_permission.widget' => 'Manage widgets',
  'admin_permission.xr_pm_products' => 'XR Product Manager: Manage products',
);