<?php
return array (
  'alert_opt_out.conversation_message_like' => 'Likes your message in a conversation',
  'alert_opt_out.post_insert' => 'Replies to a watched thread',
  'alert_opt_out.post_like' => 'Likes your message',
  'alert_opt_out.post_mention' => 'Mentions you in a message',
  'alert_opt_out.post_quote' => 'Quotes your message',
  'alert_opt_out.profile_post_comment_like' => 'Likes your profile post comment',
  'alert_opt_out.profile_post_comment_other_commenter' => 'Also comments on a profile post',
  'alert_opt_out.profile_post_comment_your_post' => 'Comments on your profile posts for other members',
  'alert_opt_out.profile_post_comment_your_profile' => 'Comments on your profile or status',
  'alert_opt_out.profile_post_insert' => 'Posts on your profile',
  'alert_opt_out.profile_post_like' => 'Likes your profile post',
  'alert_opt_out.profile_post_mention' => 'Mentions you in a profile post or comment',
  'alert_opt_out.resource_rating_reply' => 'Replies to your extension review',
  'alert_opt_out.resource_rating_review' => 'Reviews your extension',
  'alert_opt_out.resource_update_insert' => 'Updates a watched extension',
  'alert_opt_out.resource_update_like' => 'Likes your extension',
  'alert_opt_out.resource_update_mention' => 'Mentions you in a extension',
  'alert_opt_out.trophy_award' => 'Awards you a new trophy',
  'alert_opt_out.unc_approved_other' => 'Approves someone else\'s user name change',
  'alert_opt_out.unc_approved_own' => 'Approves your user name change',
  'alert_opt_out.unc_denied_own' => 'Rejects your user name change',
  'alert_opt_out.user_following' => 'Starts following you',
);