<?php
return array (
  'thread_prefix.1' => 'Direct Extension Support',
  'thread_prefix.10' => 'Rejected',
  'thread_prefix.11' => 'Voting',
  'thread_prefix.12' => 'Resource',
  'thread_prefix.13' => 'Legitimate',
  'thread_prefix.15' => 'Hack Versus Hack',
  'thread_prefix.16' => 'Giveaway',
  'thread_prefix.17' => 'Selling',
  'thread_prefix.18' => 'Buying',
  'thread_prefix.19' => 'Trading',
  'thread_prefix.2' => 'Unique Identifier Support',
  'thread_prefix.20' => 'Scammer Appeal',
  'thread_prefix.21' => 'Poll',
  'thread_prefix.22' => 'Important',
  'thread_prefix.23' => 'Verification Application',
  'thread_prefix.3' => 'Website Support',
  'thread_prefix.4' => 'Payment Support',
  'thread_prefix.5' => 'Staff Application',
  'thread_prefix.6' => 'Guide',
  'thread_prefix.7' => 'Premium Extension',
  'thread_prefix.8' => 'Free Extension',
  'thread_prefix.9' => 'Accepted',
);