<?php
return array (
  'widget.countdown_widget_key' => 'Countdown',
  'widget.discord_widget_key' => 'Paladin Extensions Discord',
  'widget.forum_overview_forum_statistics' => '',
  'widget.forum_overview_members_online' => '',
  'widget.forum_overview_new_posts' => '',
  'widget.forum_overview_new_profile_posts' => '',
  'widget.latest_followed_profile_posts' => 'Latest profile posts by followers',
  'widget.latest_posts' => 'Latest posts',
  'widget.latest_profile_posts' => 'Latest profile posts',
  'widget.latest_watched' => 'Latest watched',
  'widget.member_information' => '',
  'widget.member_wrapper_find_member' => '',
  'widget.member_wrapper_newest_members' => '',
  'widget.online_list_online_statistics' => '',
  'widget.siropu_shoutbox' => '',
  'widget.th_memberReact_reactions' => '',
  'widget.uix_footer_forumStatistics' => '',
  'widget.uix_footer_newPosts' => '',
  'widget.uix_footer_onlineStatistics' => '',
  'widget.uix_footer_sharePage' => '',
  'widget.uix_sidebar_postNewThread' => 'Want to purchase?',
  'widget.unread_posts' => 'Unread posts',
  'widget.whats_new_new_posts' => '',
  'widget.whats_new_new_profile_posts' => '',
);