<?php
return array (
  'cron_entry.EmailLog' => 'Email log',
  'cron_entry.Trader' => 'Trader',
  'cron_entry.cleanUpDaily' => 'Daily clean up',
  'cron_entry.cleanUpHourly' => 'Hourly clean up',
  'cron_entry.dailyStats' => 'Record daily statistics',
  'cron_entry.deleteExpiredBans' => 'Delete expired bans',
  'cron_entry.downgradeExpired' => 'Downgrade expired user upgrades',
  'cron_entry.emailBounce' => 'Process email bounces',
  'cron_entry.ewrDiscord' => '[8WR] Discord Account Sync',
  'cron_entry.expireTempUserChanges' => 'Expire temporary user changes',
  'cron_entry.feeder' => 'Feeder',
  'cron_entry.fileCheck' => 'Perform file health check',
  'cron_entry.forumStatistics' => 'Rebuild forum statistics',
  'cron_entry.memberStatsCache' => 'Rebuild member stats cache',
  'cron_entry.mjstEscalation' => '[BRST] Escalations',
  'cron_entry.run_successfully' => 'Cron entry was run successfully.',
  'cron_entry.siropuShoutboxPrune' => 'Shoutbox: Auto prune',
  'cron_entry.siropuShoutboxShout' => 'Shoutbox: Delete older shouts',
  'cron_entry.sitemap' => 'Rebuild sitemap',
  'cron_entry.srcContest' => 'Referral Contests: Contest',
  'cron_entry.steamAuthCleanup' => 'SteamAuth: Cleanup',
  'cron_entry.steamAuthUpdateUserGames' => 'SteamAuth: Update User Games',
  'cron_entry.th_updateCheck_uix' => '[TH] UI.X: Check for updates',
  'cron_entry.trophy' => 'Update user trophies',
  'cron_entry.userGroupPromotions' => 'User group promotions',
  'cron_entry.views' => 'Update view counters',
  'cron_entry.warningExpiry' => 'Handle expired warnings',
  'cron_entry.xr_pm_expiry' => 'XR PM: Handle purchase expiry',
);