<?php
return array (
  'permission_interface.EWRdiscord' => '[8WR] Discord Integration',
  'permission_interface.ahDW_perms' => '[AH] Discord Widget',
  'permission_interface.conversationModeratorPermissions' => 'Conversation moderator permissions',
  'permission_interface.conversationPermissions' => 'Conversation permissions',
  'permission_interface.countdown' => 'Countdown',
  'permission_interface.emailLog' => 'Email log',
  'permission_interface.forumModeratorPermissions' => 'Forum moderator permissions',
  'permission_interface.forumPermissions' => 'Forum permissions',
  'permission_interface.generalModeratorPermissions' => 'General moderator permissions',
  'permission_interface.generalPermissions' => 'General permissions',
  'permission_interface.history' => 'History',
  'permission_interface.klAMDP' => 'Auto Double Post Merger permissions',
  'permission_interface.mjstKbModeratorPermission' => '[BRST] Knowledge base moderator permissions',
  'permission_interface.mjstKbPermission' => '[BRST] Knowledge base permissions',
  'permission_interface.mjstTicketModeratorPermission' => '[BRST] Support ticket moderator permissions',
  'permission_interface.mjstTicketPermission' => '[BRST] Support ticket permissions',
  'permission_interface.postAttachmentPermissions' => 'Post attachment permissions',
  'permission_interface.profilePostModeratorPermissions' => 'Profile post moderator permissions',
  'permission_interface.profilePostPermissions' => 'Profile post permissions',
  'permission_interface.signaturePermissions' => 'Signature permissions',
  'permission_interface.similarThreads' => 'Similar threads',
  'permission_interface.siropuReferralContests' => 'Referral Contests',
  'permission_interface.siropuShoutbox' => 'Shoutbox',
  'permission_interface.steamauth' => 'Steam Auth',
  'permission_interface.thReactionsModerator' => '[TH] Reactions moderator permissions',
  'permission_interface.thReactionsPermissions' => '[TH] Reactions permissions',
  'permission_interface.th_uix' => 'UI.X Permissions',
  'permission_interface.xr_pm_user' => 'XR Product Manager: User permissions',
);