<?php
return array (
  'permission_interface.EWRdiscord' => '[8WR] Discord Integration',
  'permission_interface.conversationModeratorPermissions' => 'Conversation moderator permissions',
  'permission_interface.conversationPermissions' => 'Conversation permissions',
  'permission_interface.conversationView' => 'Conversation view',
  'permission_interface.countdown' => 'Countdown',
  'permission_interface.deletePosts' => 'Delete posts',
  'permission_interface.emailLog' => 'Email log',
  'permission_interface.forumModeratorPermissions' => 'Forum moderator permissions',
  'permission_interface.forumPermissions' => 'Forum permissions',
  'permission_interface.generalModeratorPermissions' => 'General moderator permissions',
  'permission_interface.generalPermissions' => 'General permissions',
  'permission_interface.history' => 'History',
  'permission_interface.klAMDP' => 'Auto Double Post Merger permissions',
  'permission_interface.memberNotes' => 'Member notes',
  'permission_interface.postAttachmentPermissions' => 'Post attachment permissions',
  'permission_interface.profilePostModeratorPermissions' => 'Profile post moderator permissions',
  'permission_interface.profilePostPermissions' => 'Profile post permissions',
  'permission_interface.resourceModeratorPermissions' => 'Resource moderator permissions',
  'permission_interface.resourcePermissions' => 'Resource permissions',
  'permission_interface.signaturePermissions' => 'Signature permissions',
  'permission_interface.similarThreads' => 'Similar threads',
  'permission_interface.siropuReferralContests' => 'Referral Contests',
  'permission_interface.siropuShoutbox' => 'Shoutbox',
  'permission_interface.thReactionsModerator' => '[TH] Reactions moderator permissions',
  'permission_interface.thReactionsPermissions' => '[TH] Reactions permissions',
  'permission_interface.th_bookmarks' => '[TH] Bookmarks',
  'permission_interface.th_uix' => 'UI.X Permissions',
  'permission_interface.xfv_thread_starter' => '[xFv] Thread Starter',
);