<?php
return array (
  'widget_def.ahDiscordWidget' => '[AH] Discord Widget',
  'widget_def.birthdays' => 'Today\'s birthdays',
  'widget_def.countdown' => 'Countdown',
  'widget_def.find_member' => 'Find member',
  'widget_def.forum_statistics' => 'Forum statistics',
  'widget_def.html' => 'HTML',
  'widget_def.memberNotes' => 'Member notes',
  'widget_def.member_stat' => 'Member stat',
  'widget_def.members_online' => 'Members online',
  'widget_def.new_posts' => 'New posts',
  'widget_def.new_profile_posts' => 'New profile posts',
  'widget_def.new_threads' => 'New threads',
  'widget_def.newest_members' => 'Newest members',
  'widget_def.online_statistics' => 'Online statistics',
  'widget_def.php_callback' => 'PHP callback',
  'widget_def.share_page' => 'Share this page',
  'widget_def.similarThreads' => 'Similar threads',
  'widget_def.siropu_referral_contests' => 'Referral Contests: Contests',
  'widget_def.siropu_referral_link' => 'Referral Contests: Referral link',
  'widget_def.siropu_referral_top_ref' => 'Referral Contests: Top referrers',
  'widget_def.siropu_shoutbox' => 'Shoutbox',
  'widget_def.template_syntax' => 'Template syntax',
  'widget_def.th_bookmarks' => 'Bookmarks',
  'widget_def.th_memberReact_reactions' => '[TH] Reactions: Member reactions',
  'widget_def.th_post_thread_uix' => '[UI.X] Start a thread',
  'widget_def.th_widget_login_uix' => '[UI.X] Login form',
  'widget_def.thread_poll' => 'Thread poll',
  'widget_def.thuix_socialMedia' => '[TH] UI.X social media feed',
  'widget_def.visitor_panel' => 'Visitor panel',
  'widget_def.xfrm_latest_reviews' => 'XFRM: Latest reviews',
  'widget_def.xfrm_new_resources' => 'XFRM: New resources',
  'widget_def.xfrm_top_resources' => 'XFRM: Top Resources',
);