#pragma once
#include <Windows.h>
#include <TlHelp32.h>
#include <iostream>
#include <thread>
#include <atomic>
#include <ctime>
#include "Aimbot.h"
#include "Trigger.h"
#include "RCS.h"
#include "ESP.h"
#include "Misc.h"
#include "Skins.h"
